- name: Install SSH GSSAPI package
  become: true
  ansible.builtin.apt:
    pkg: openssh-server-gssapi
    install_recommends: no
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '13'
  notify: "ssh.gssapi : Restart sshd"

- name: Enable GSSAPI Authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "GSSAPIAuthentication"
    line: GSSAPIAuthentication yes
    insertbefore: "GSSAPI"
  notify: "ssh.gssapi : Restart sshd"
